In [3]:
library(tidyverse)
library(ggplot2)
library(data.table)
library(dtplyr)
library(arrow)

In [ ]:
files <- list.files(path = "D:/BNC Full Data/12-9_10AM Run/CSV",
                    pattern = "\\.csv$",
                    full.names = TRUE)

df_combined <- read_csv(files, id = "file_name")

write_rds(df_combined, "D:/BNC Full Data, 12-10 8PM Run/12-10 8PM Unprocessed Data.rds")
write_parquet(df_combined, "Results 12-10 8PM/12-10 8PM Unprocessed Data.parquet")

Rows: 106513970 Columns: 44
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (21): Sentence_ID, Filename, Modality, Sentence_Text, Word_Token, Phrase...
dbl (18): Sent_Verb_Count, Sent_Auxiliary_Count, Sent_Subject_Count, Sent_To...
lgl  (4): Sent_Transitive, Is_NP, NP_Is_Bare_NP, Is_Head_Noun

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message in saveRDS(x, con, version = version, refhook = refhook, ascii = text):
"cannot open file 'D:/BNC Full Data, 12-10 8PM Run/12-10 8PM Unprocessed Data.rds': No such file or directory"

ERROR: Error in saveRDS(x, con, version = version, refhook = refhook, ascii = text): cannot open the connection

:

In [ ]:
summary(df_combined)

  file_name         Sentence_ID          Filename           Modality
 Length:106045470   Length:106045470   Length:106045470   Length:106045470
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 Sentence_Text      Sent_Verb_Count Sent_Auxiliary_Count Sent_Subject_Count
 Length:106045470   Min.   : 0.00   Min.   : 0.000       Min.   : 0.000
 Class :character   1st Qu.: 2.00   1st Qu.: 1.000       1st Qu.: 1.000
 Mode  :character   Median : 3.00   Median : 1.000       Median : 2.000
                    Mean   : 3.07   Mean   : 1.662       Mean   : 1.917
                    3rd Qu.: 4.00   3rd Qu.: 2.000       3rd Qu.: 3.000
                    Max.   :61.00   Max.   :46.000       Max.   :52.000

 Sent_Tot_Obj_Count Sent_Dir_Object_Count Sent_Ind_Object_Count
 Min.   : 0.000     Min.   : 0.000        Min.   :0.00000
 1st Qu.: 0.000     1st Qu.: 0.000        1st Qu.:0.00000
 Median : 1.000     Median : 1.000        Median :0.00000
 Mean   : 1.225     Mean   : 1.189        Mean   :0.03573
 3rd Qu.: 2.000     3rd Qu.: 2.000        3rd Qu.:0.00000
 Max.   :38.000     Max.   :38.000        Max.   :5.00000

 Sent_Transitive  Sent_Comma_Count  Sent_Sub_Conj_Count Sent_Coord_Conj_Count
 Mode :logical    Min.   :  0.000   Min.   : 0.0000     Min.   : 0.000
 FALSE:35139793   1st Qu.:  0.000   1st Qu.: 0.0000     1st Qu.: 0.000
 TRUE :70905677   Median :  1.000   Median : 0.0000     Median : 1.000
                  Mean   :  1.538   Mean   : 0.6013     Mean   : 1.084
                  3rd Qu.:  2.000   3rd Qu.: 1.0000     3rd Qu.: 2.000
                  Max.   :124.000   Max.   :20.0000     Max.   :41.000

 Sent_Relative_Clause_Count Sent_Adv_Clause_Count Clausal_Complement_Count
 Min.   : 0.0000            Min.   : 0.0000       Min.   : 0.0000
 1st Qu.: 0.0000            1st Qu.: 0.0000       1st Qu.: 0.0000
 Median : 0.0000            Median : 0.0000       Median : 0.0000
 Mean   : 0.3425            Mean   : 0.4975       Mean   : 0.4426
 3rd Qu.: 1.0000            3rd Qu.: 1.0000       3rd Qu.: 1.0000
 Max.   :15.0000            Max.   :10.0000       Max.   :19.0000

 Sent_Prep_Phrase_Count Word_Token_Index  Word_Token        Phrase_Token
 Min.   : 0.00          Min.   :  0.00   Length:106045470   Length:106045470
 1st Qu.: 1.00          1st Qu.:  5.00   Class :character   Class :character
 Median : 3.00          Median : 12.00   Mode  :character   Mode  :character
 Mean   : 3.24          Mean   : 15.15
 3rd Qu.: 4.00          3rd Qu.: 21.00
 Max.   :90.00          Max.   :649.00

 Phrase_Surprisal   Word_Surprisal      Word_Lemma          Word_POS
 Min.   : 0.0       Min.   : 0.0       Length:106045470   Length:106045470
 1st Qu.:14.0       1st Qu.:13.6       Class :character   Class :character
 Median :15.9       Median :15.7       Mode  :character   Mode  :character
 Mean   :16.5       Mean   :16.5
 3rd Qu.:18.4       3rd Qu.:18.8
 Max.   :64.8       Max.   :64.8
 NA's   :29448448   NA's   :30338706
 Word_Dependency      Is_NP          NP_Is_Bare_NP    NP_Structure
 Length:106045470   Mode :logical    Mode :logical    Length:106045470
 Class :character   FALSE:55660403   FALSE:28835357   Class :character
 Mode  :character   TRUE :50385067   TRUE :21549710   Mode  :character
                                     NA's :55660403



 NP_Head_Lemma      NP_Det_Lemma       NP_Head_POS         NP_Det_POS
 Length:106045470   Length:106045470   Length:106045470   Length:106045470
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 NP_Head_Dependency NP_Det_Dependency  NP_Head_Text       NP_Det_Text
 Length:106045470   Length:106045470   Length:106045470   Length:106045470
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 NP_Sum_Surprisal   NP_Mean_Surprisal  NP_Argument         NP_Number
 Min.   :  0        Min.   : 0         Length:106045470   Length:106045470
 1st Qu.: 25        1st Qu.:14         Class :character   Class :character
 Median : 36        Median :16         Mode  :character   Mode  :character
 Mean   : 42        Mean   :17
 3rd Qu.: 53        3rd Qu.:18
 Max.   :541        Max.   :54
 NA's   :67636960   NA's   :67636960
 NP_Definiteness    Is_Head_Noun
 Length:106045470   Mode :logical
 Class :character   FALSE:24413059
 Mode  :character   TRUE :25972008
                    NA's :55660403

In [ ]:
# Creating Tags for first element in each NP

df_processed <- df_combined %>% 
    arrange(Sentence_ID, Word_Token_Index) %>% 
    group_by(Sentence_ID) %>% 
    mutate(
        prev_is_NP = lag(Is_NP, default = FALSE),
        prev_NP_Head_Text = lag(NP_Head_Text),

        first_token_of_NP = Is_NP & (!prev_is_NP | NP_Head_Text != prev_NP_Head_Text)
    ) %>% 
    ungroup() %>% 
    select(-prev_is_NP, -prev_NP_Head_Text) %>% 
#Propogates index of first NP down to the full phrase
    group_by(Sentence_ID, np_id = consecutive_id(Phrase_Token)) %>% 
    mutate(
        np_start_idx = ifelse(
            is.na (Phrase_Token) | Is_NP == FALSE, 
            NA,
            min(Word_Token_Index)
        )
    ) %>% 
    ungroup() %>% 
    select(-np_id) %>% 
# Creates within_file IDS and Within Chunk Ids
    mutate(
        within_file_id = str_extract(Sentence_ID, "(?<=_)\\d+") %>% 
        as.integer
    ) 

# Remove duplicate sentences:

df_processed <- df_processed %>% 
    arrange(Sentence_ID) %>% 
        group_by(Sentence_Text) %>%
        mutate(first_Sentence_ID = first(Sentence_ID)) %>%
        filter(Sentence_ID == first_Sentence_ID) %>%
        ungroup() %>%
        select(-first_Sentence_ID)

In [ ]:
summary(df_processed)

  file_name         Sentence_ID          Filename           Modality
 Length:103426691   Length:103426691   Length:103426691   Length:103426691
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 Sentence_Text      Sent_Verb_Count  Sent_Auxiliary_Count Sent_Subject_Count
 Length:103426691   Min.   : 0.000   Min.   : 0.00        Min.   : 0.000
 Class :character   1st Qu.: 2.000   1st Qu.: 1.00        1st Qu.: 1.000
 Mode  :character   Median : 3.000   Median : 1.00        Median : 2.000
                    Mean   : 3.072   Mean   : 1.66        Mean   : 1.919
                    3rd Qu.: 4.000   3rd Qu.: 2.00        3rd Qu.: 3.000
                    Max.   :61.000   Max.   :46.00        Max.   :52.000

 Sent_Tot_Obj_Count Sent_Dir_Object_Count Sent_Ind_Object_Count
 Min.   : 0.000     Min.   : 0.00         Min.   :0.00000
 1st Qu.: 0.000     1st Qu.: 0.00         1st Qu.:0.00000
 Median : 1.000     Median : 1.00         Median :0.00000
 Mean   : 1.226     Mean   : 1.19         Mean   :0.03563
 3rd Qu.: 2.000     3rd Qu.: 2.00         3rd Qu.:0.00000
 Max.   :38.000     Max.   :38.00         Max.   :5.00000

 Sent_Transitive  Sent_Comma_Count  Sent_Sub_Conj_Count Sent_Coord_Conj_Count
 Mode :logical    Min.   :  0.000   Min.   : 0.0000     Min.   : 0.000
 FALSE:34092241   1st Qu.:  0.000   1st Qu.: 0.0000     1st Qu.: 0.000
 TRUE :69334450   Median :  1.000   Median : 0.0000     Median : 1.000
                  Mean   :  1.541   Mean   : 0.6003     Mean   : 1.082
                  3rd Qu.:  2.000   3rd Qu.: 1.0000     3rd Qu.: 2.000
                  Max.   :124.000   Max.   :20.0000     Max.   :41.000

 Sent_Relative_Clause_Count Sent_Adv_Clause_Count Clausal_Complement_Count
 Min.   : 0.0000            Min.   : 0.0000       Min.   : 0.0000
 1st Qu.: 0.0000            1st Qu.: 0.0000       1st Qu.: 0.0000
 Median : 0.0000            Median : 0.0000       Median : 0.0000
 Mean   : 0.3423            Mean   : 0.4979       Mean   : 0.4429
 3rd Qu.: 1.0000            3rd Qu.: 1.0000       3rd Qu.: 1.0000
 Max.   :15.0000            Max.   :10.0000       Max.   :19.0000

 Sent_Prep_Phrase_Count Word_Token_Index  Word_Token        Phrase_Token
 Min.   : 0.000         Min.   :  0.00   Length:103426691   Length:103426691
 1st Qu.: 1.000         1st Qu.:  5.00   Class :character   Class :character
 Median : 3.000         Median : 12.00   Mode  :character   Mode  :character
 Mean   : 3.245         Mean   : 15.17
 3rd Qu.: 4.000         3rd Qu.: 21.00
 Max.   :90.000         Max.   :649.00

 Phrase_Surprisal   Word_Surprisal      Word_Lemma          Word_POS
 Min.   : 0.0       Min.   : 0.0       Length:103426691   Length:103426691
 1st Qu.:13.9       1st Qu.:13.6       Class :character   Class :character
 Median :15.9       Median :15.7       Mode  :character   Mode  :character
 Mean   :16.4       Mean   :16.4
 3rd Qu.:18.3       3rd Qu.:18.7
 Max.   :64.8       Max.   :64.8
 NA's   :28720266   NA's   :29591202
 Word_Dependency      Is_NP          NP_Is_Bare_NP    NP_Structure
 Length:103426691   Mode :logical    Mode :logical    Length:103426691
 Class :character   FALSE:54200890   FALSE:28217823   Class :character
 Mode  :character   TRUE :49225801   TRUE :21007978   Mode  :character
                                     NA's :54200890



 NP_Head_Lemma      NP_Det_Lemma       NP_Head_POS         NP_Det_POS
 Length:103426691   Length:103426691   Length:103426691   Length:103426691
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 NP_Head_Dependency NP_Det_Dependency  NP_Head_Text       NP_Det_Text
 Length:103426691   Length:103426691   Length:103426691   Length:103426691
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 NP_Sum_Surprisal   NP_Mean_Surprisal  NP_Argument         NP_Number
 Min.   :  0        Min.   : 0         Length:103426691   Length:103426691
 1st Qu.: 25        1st Qu.:14         Class :character   Class :character
 Median : 36        Median :16         Mode  :character   Mode  :character
 Mean   : 42        Mean   :17
 3rd Qu.: 53        3rd Qu.:18
 Max.   :541        Max.   :54
 NA's   :65927378   NA's   :65927378
 NP_Definiteness    Is_Head_Noun     first_token_of_NP  np_start_idx
 Length:103426691   Mode :logical    Mode :logical     Min.   :  0
 Class :character   FALSE:23885580   FALSE:95285172    1st Qu.:  4
 Mode  :character   TRUE :25340221   TRUE :8141491     Median : 11
                    NA's :54200890   NA's :28          Mean   : 14
                                                       3rd Qu.: 20
                                                       Max.   :645
                                                       NA's   :54200890
 within_file_id  within_chunk_id
 Min.   :  1.0   Min.   :  1.0
 1st Qu.:120.0   1st Qu.:105.0
 Median :254.0   Median :237.0
 Mean   :264.9   Mean   :248.3
 3rd Qu.:404.0   3rd Qu.:385.0
 Max.   :582.0   Max.   :550.0

In [ ]:
write_rds(df_processed, "D:/BNC Full Data, 12-10 8PM Run/12-10 8PM Processed Data.rds")
write_parquet(df_processed, "Results 12-10 8PM/12-10 8PM Processed Data.parquet")

In [ ]:
df_sentences <- df_processed %>% 
    filter(
        Modality == "written", 
        Sent_Verb_Count == 1,
        Sent_Auxiliary_Count == 0,
        Sent_Subject_Count == 1,
        Sent_Tot_Obj_Count %in% 1,
        Sent_Dir_Object_Count == 1 ,
        Sent_Ind_Object_Count == 0,
        Sent_Sub_Conj_Count == 0,
        Sent_Coord_Conj_Count == 0, 
        Clausal_Complement_Count == 0,
        Sent_Relative_Clause_Count == 0, 
        Sent_Adv_Clause_Count == 0, 
        Sent_Prep_Phrase_Count == 0,
        Sent_Comma_Count == 0,
        !str_detect(Sentence_Text, "\\?"),
        Sent_Transitive == TRUE,
    )

df_sentences <- df_sentences %>% 
    mutate(
        definiteness = factor(NP_Definiteness,
        levels = c("indefinite", "definite"),
        labels = c("indef", "def"))
    ) %>% 
    mutate(
        argPos = factor(
            NP_Argument,
            levels = c("dir_object", "subject"),
            labels = c("obj", "sbj")
        )
    ) %>% 
    mutate(surprisal = Phrase_Surprisal) %>% 
    select(Sentence_ID, Sentence_Text, Phrase_Token, Word_Token, Word_Token_Index, Word_Surprisal, surprisal, definiteness, argPos, np_start_idx, within_file_id, within_chunk_id, Is_NP, Is_Head_Noun)

summary(df_sentences)

 Sentence_ID        Sentence_Text      Phrase_Token        Word_Token
 Length:268332      Length:268332      Length:268332      Length:268332
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 Word_Token_Index Word_Surprisal     surprisal      definiteness
 Min.   : 0.000   Min.   : 0.014   Min.   : 0.014   indef: 41354
 1st Qu.: 1.000   1st Qu.:13.359   1st Qu.:13.831   def  :101264
 Median : 3.000   Median :15.695   Median :15.828   NA's :125714
 Mean   : 2.892   Mean   :16.403   Mean   :16.402
 3rd Qu.: 4.000   3rd Qu.:18.828   3rd Qu.:18.365
 Max.   :21.000   Max.   :53.469   Max.   :49.062
                  NA's   :60401    NA's   :57197
  argPos        np_start_idx    within_file_id  within_chunk_id   Is_NP
 obj : 85555   Min.   : 0.000   Min.   :  1.0   Min.   :  1.0   Mode :logical
 sbj : 61567   1st Qu.: 0.000   1st Qu.:136.0   1st Qu.:117.0   FALSE:117777
 NA's:121210   Median : 2.000   Median :270.0   Median :251.0   TRUE :150555
               Mean   : 1.807   Mean   :277.5   Mean   :258.5
               3rd Qu.: 3.000   3rd Qu.:416.0   3rd Qu.:394.0
               Max.   :20.000   Max.   :582.0   Max.   :550.0
               NA's   :117777
 Is_Head_Noun
 Mode :logical
 FALSE:64315
 TRUE :86240
 NA's :117777

In [ ]:

write_rds(df_sentences, "D:/BNC Full Data, 12-10 8PM Run/12-10 8PM Filtered All Tokens Data.rds")
write_parquet(df_sentences, "Results 12-10 8PM/12-10 8PM All Tokens Data.parquet")

In [ ]:
df_nps <- df_sentences %>% 
    filter(
        Is_NP == TRUE,
        Is_Head_Noun == TRUE,
        definiteness %in% c("def", "indef"),
        argPos %in% c("obj", "sbj"),
        !is.na(surprisal),
    ) %>% 
    group_by(Sentence_ID) %>% # Drops sentences without one subject and one object
        filter(n() == 2 & n_distinct(argPos) == 2) %>%
        ungroup()

In [ ]:
write_rds(df_nps, "D:/BNC Full Data, 12-10 8PM Run/12-10 8PM NP only.rds")
write_parquet(df_sentences, "Results 12-10 8PM/12-10 8PM NP Only.parquet")

### Analyses and Plots

In [ ]:

# library(ggeffects)
    plotFont <- function(fontBase) { # Easy way to adjust font size for plots
        theme( # Add as a final ggplot object (no parentheses)
        plot.title = element_text(size = 14*fontBase),      # Title font size
        axis.title.x = element_text(size = 12*fontBase),    # X-axis title font size
        axis.title.y = element_text(size = 12*fontBase),    # Y-axis title font size
        axis.text.x = element_text(size = 10*fontBase),     # X-axis tick labels font size
        axis.text.y = element_text(size = 10*fontBase),     # Y-axis tick labels font size
        legend.text = element_text(size = 10*fontBase),     # Legend text size
        legend.title = element_text(size = 10*fontBase),    # Legend title size
        strip.text = element_text(size = 10*fontBase)
        )
    }

In [ ]:
count_table <- df_nps %>% 
    count(argPos, definiteness)
count_table

  argPos definiteness n
1 obj    indef         899
2 obj    def           794
3 sbj    indef         383
4 sbj    def          1310

In [ ]:
mod_NP_Index <- lm(data=df_nps, surprisal ~ definiteness * argPos * np_start_idx)

summary(mod_NP_Index)

Call:
lm(formula = surprisal ~ definiteness * argPos * np_start_idx,
    data = df_nps)

Residuals:
     Min       1Q   Median       3Q      Max
-12.8160  -2.4721  -0.2779   2.1431  18.4841

Coefficients:
                                       Estimate Std. Error t value Pr(>|t|)
(Intercept)                             15.3990     0.3112  49.483  < 2e-16 ***
definitenessdef                         -0.7413     0.4562  -1.625  0.10430
argPossbj                                1.6067     0.3665   4.383  1.2e-05 ***
np_start_idx                            -0.1664     0.0900  -1.849  0.06461 .
definitenessdef:argPossbj                1.5125     0.5076   2.980  0.00291 **
definitenessdef:np_start_idx             0.1775     0.1341   1.324  0.18554
argPossbj:np_start_idx                   0.1097     0.3859   0.284  0.77629
definitenessdef:argPossbj:np_start_idx  -0.5582     0.4317  -1.293  0.19608
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.719 on 3378 degrees of freedom
Multiple R-squared:  0.1244,	Adjusted R-squared:  0.1225
F-statistic: 68.53 on 7 and 3378 DF,  p-value: < 2.2e-16

In [ ]:
mod_token_index <- lm(data = df_sentences, log(Word_Surprisal) ~ Word_Token_Index)

summary(mod_token_index)

Call:
lm(formula = log(Word_Surprisal) ~ Word_Token_Index, data = df_sentences)

Residuals:
    Min      1Q  Median      3Q     Max
-7.0281 -0.1642 -0.0030  0.1782  1.2197

Coefficients:
                   Estimate Std. Error t value Pr(>|t|)
(Intercept)       2.7804634  0.0010075 2759.84   <2e-16 ***
Word_Token_Index -0.0105505  0.0003257  -32.39   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2973 on 207929 degrees of freedom
  (60401 observations deleted due to missingness)
Multiple R-squared:  0.005022,	Adjusted R-squared:  0.005017
F-statistic:  1049 on 1 and 207929 DF,  p-value: < 2.2e-16

In [ ]:
options(repr.plot.width = 12, repr.plot.height = 8)

plot <- ggplot(data = df, aes(x = argPos, y = surprisal, fill = definiteness)) +
    geom_boxplot(outlier.shape = NA) +
        coord_cartesian(ylim = c(0, 35)) +
    labs(
        title = "Argument Position, Definiteness, and Surprisal",
        x = "Argument Position",
        y = "Surprisal",
        fill = "Definiteness"
    ) + 
    scale_x_discrete(labels = c("sbj" = "Subject", "obj" = "Object")) +
    scale_fill_discrete(labels = c("def" = "Definite", "indef" = "Indefinite"))+
    plotFont(3) 


plot

In [6]:
df <- open_dataset("Old or lost files/Results 12-9 5PM/12-9_5PM_Full-Data_UNPROCESSED.parquet") %>% collect()

In [7]:
head(df)

  file_name                                 Sentence_ID Filename Modality
1 D:/BNC Full Data/12-9_5PM Run/CSV/A00.csv A00_0001    A00.xml  written
2 D:/BNC Full Data/12-9_5PM Run/CSV/A00.csv A00_0001    A00.xml  written
3 D:/BNC Full Data/12-9_5PM Run/CSV/A00.csv A00_0001    A00.xml  written
4 D:/BNC Full Data/12-9_5PM Run/CSV/A00.csv A00_0001    A00.xml  written
5 D:/BNC Full Data/12-9_5PM Run/CSV/A00.csv A00_0001    A00.xml  written
6 D:/BNC Full Data/12-9_5PM Run/CSV/A00.csv A00_0001    A00.xml  written
  Sentence_Text
1 is a condition caused by a virus called HIV ( Human Immuno Deficiency Virus ) .
2 is a condition caused by a virus called HIV ( Human Immuno Deficiency Virus ) .
3 is a condition caused by a virus called HIV ( Human Immuno Deficiency Virus ) .
4 is a condition caused by a virus called HIV ( Human Immuno Deficiency Virus ) .
5 is a condition caused by a virus called HIV ( Human Immuno Deficiency Virus ) .
6 is a condition caused by a virus called HIV ( Human Immuno Deficiency Virus ) .
  Sent_Verb_Count Sent_Auxiliary_Count Sent_Subject_Count Sent_Tot_Obj_Count
1 2               1                    0                  0
2 2               1                    0                  0
3 2               1                    0                  0
4 2               1                    0                  0
5 2               1                    0                  0
6 2               1                    0                  0
  Sent_Dir_Object_Count ⋯ NP_Head_Dependency NP_Det_Dependency NP_Head_Text
1 0                     ⋯ NA                 NA                NA
2 0                     ⋯ attr               det               condition
3 0                     ⋯ attr               det               condition
4 0                     ⋯ NA                 NA                NA
5 0                     ⋯ NA                 NA                NA
6 0                     ⋯ pobj               det               virus
  NP_Det_Text NP_Sum_Surprisal NP_Mean_Surprisal NP_Argument NP_Number
1 NA                NA               NA          NA          NA
2 a           25.90625         12.95312          non-arg     singular
3 a           25.90625         12.95312          non-arg     singular
4 NA                NA               NA          NA          NA
5 NA                NA               NA          NA          NA
6 a           28.56250         14.28125          prep_object singular
  NP_Definiteness Is_Head_Noun
1 NA                 NA
2 indefinite      FALSE
3 indefinite       TRUE
4 NA                 NA
5 NA                 NA
6 indefinite      FALSE

In [ ]:
df %>% 
    count(Filename, sort = TRUE)

     Filename n
1    HHV.xml  471934
2    HHX.xml  443991
3    K97.xml  391894
4    HHW.xml  355598
5    CRM.xml  329289
6    HH3.xml  323448
7    K5D.xml  319256
8    K5M.xml  290143
9    CBF.xml  275478
10   CBG.xml  275350
11   CBC.xml  270619
12   K4W.xml  243930
13   HWF.xml  237013
14   K4T.xml  235702
15   CEP.xml  231410
16   HJ4.xml  225483
17   HU3.xml  216105
18   K52.xml  209130
19   HAC.xml  207807
20   CH2.xml  201937
21   HWS.xml  198905
22   HU2.xml  195504
23   K55.xml  193540
24   HJ0.xml  191377
25   K5A.xml  186320
26   HLD.xml  185763
27   HJ3.xml  177551
28   HU4.xml  171659
29   HL7.xml  166860
30   CH1.xml  163172
⋮    ⋮        ⋮
3100 HRL.xml  241
3101 K3F.xml  230
3102 A82.xml  204
3103 HNU.xml  199
3104 K2S.xml  196
3105 HBA.xml  195
3106 HBY.xml  195
3107 K30.xml  178
3108 G11.xml  173
3109 HKN.xml  173
3110 HJS.xml  168
3111 K3R.xml  161
3112 J5K.xml  149
3113 HKH.xml  148
3114 J1W.xml  146
3115 B1C.xml  140
3116 HKJ.xml  119
3117 J0Y.xml  106
3118 AHH.xml  101
3119 A9B.xml   79
3120 HKC.xml   69
3121 FAS.xml   67
3122 J0R.xml   47
3123 HNP.xml   42
3124 HNX.xml   18
3125 HD9.xml   13
3126 FU5.xml    9
3127 G1V.xml    6
3128 A9G.xml    2
3129 HP1.xml    2

: